# Generated by Django 4.1.5 on 2023-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=255)),
                ('tabela', models.CharField(choices=[('000', 'Selecionar...'), ('001', 'Tabela Estado'), ('002', 'Tabela Cor'), ('003', 'Tabela Tamanho')], default='000', max_length=3)),
            ],
        ),
    ]
